language: objective-c #1
<<<<<<< HEAD
=======
#osx_image: xcode8 #2
>>>>>>> origin/travis-setup
xcode_project: RetroCalc.xcodeproj #3
xcode_scheme: RetroCalc #4
xcode_sdk: iphonesimulator9.3 #5

script:
  - ls -al Rakefile
  - rake test:ios
  - rake test:osx
  - rake test:xctool_ios
